### ISSUE TITLE
Week 1 作業回覆

### ISSUE THREAD

**Issue by azole** [CashYang0708/git-practice#1]
1. readme.md
readme.md 中的第二小題，是希望可以了解你自己對這門課的期許（希望這學期過去，自己變成什麼樣子、學到什麼東西），第一堂課有強調，這門課很看你們對自己的要求，你對自己要求高，就能學得多，課堂上更多的是「你教我」，而不是我教你，你可以再想想看這門課適不適合你喔。

如果有想要繼續修這門課，那請你試著告訴你，這學期過去，你期許自己變成怎麼樣的人？

2. git.md
這份報告內容大致正確，但深度不足，你可以自行決定就停在這邊、拿個及格分數(60)，或是多一點好奇心，試著多問自己幾個問題，也實際舉例說明整個 git 底層的運做原理看看，做不做、要研究到多深入，你自己決定。

3. git.md
> 我認為commit message基本上就是寫你這次commit所做的事情，以我的個人經驗來說，通常一個commit來說，我不會新增超過三個檔案，這樣之後有問題的話trace back會比較方便一點。至於style方面，如果能夠有issue的編號當作參考會更方便了解這個commit在做的事情

- issue 編號之外，還有沒有其他合適的資訊？你有沒有上網參考過大型軟體公司們怎麼建議的？
- 新增不超過三個檔案，那如果這次的 commit (不超過三個檔案) 是會讓團隊夥伴 pull 下來後，系統是壞掉的，那怎麼辦？

**Comment by CashYang0708** [comment]
教授您好，根據您上述的留言我有做相對應的修改，麻煩請您再撥空查看謝謝!

**Comment by azole** [comment]
1. 排版上要注意
2. 實驗觀察部分，可以把自己做實驗過程中看到的內容，透過複製或截圖紀錄在文件裡，這會是你自己獨一無二的內容，這才是最珍貴的部分，下次有類似的作業，務必試試看。

如果沒有其他要跟我討論的部分，這個 issue 可以 close 了。
